version: v1
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MAC_ADDR='your mac address'
      - BROADCAST_IP_ADDR='broadcast ip'
    restart: always
    ports:
      - 8080:8080
